"""Heuristics for flagging AI-assisted work from PR/commit metadata, and
comparing outcomes for AI-assisted vs. non-AI-assisted work.

This is deliberately simple and transparent about its limits: it pattern
matches on commit trailers, PR bodies, and labels for known AI-tool
signatures. It will under-count silent AI usage and can be fooled by
noise -- treat it as a directional signal, the same way DX's own AI code
insights are explicit about needing multiple corroborating signals.
"""

from __future__ import annotations

from typing import Any

AI_SIGNALS = (
    "co-authored-by: claude",
    "co-authored-by: copilot",
    "co-authored-by: cursor",
    "generated with copilot",
    "generated by copilot",
    "github copilot",
    "cursor ai",
    "chatgpt",
    "claude code",
    "ai-assisted",
    "ai-generated",
)

AI_LABELS = ("ai-assisted", "copilot", "ai-generated")


def is_ai_assisted(pr: dict[str, Any]) -> bool:
    text = " ".join(
        filter(None, [pr.get("title"), pr.get("body")])
    ).lower()
    if any(sig in text for sig in AI_SIGNALS):
        return True
    labels = [l.get("name", "").lower() for l in pr.get("labels", [])]
    return any(label in AI_LABELS for label in labels)


def split_by_ai_assist(prs: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    ai, non_ai = [], []
    for pr in prs:
        (ai if is_ai_assisted(pr) else non_ai).append(pr)
    return ai, non_ai


def ai_impact_summary(prs: list[dict[str, Any]]) -> dict[str, Any]:
    from .metrics import _hours_between, _median, merged_prs  # local import to avoid cycle at module load

    merged = merged_prs(prs)
    ai, non_ai = split_by_ai_assist(merged)

    def cycle_times(items: list[dict[str, Any]]) -> list[float]:
        return [
            h for p in items
            if (h := _hours_between(p.get("created_at"), p.get("merged_at"))) is not None
        ]

    ai_cycle = _median(cycle_times(ai))
    non_ai_cycle = _median(cycle_times(non_ai))

    delta_pct = None
    if ai_cycle is not None and non_ai_cycle:
        delta_pct = round((ai_cycle - non_ai_cycle) / non_ai_cycle * 100, 1)

    return {
        "ai_assisted_pr_count": len(ai),
        "non_ai_pr_count": len(non_ai),
        "pct_prs_ai_assisted": None if not merged else round(len(ai) / len(merged) * 100, 1),
        "median_cycle_time_hours_ai_assisted": ai_cycle,
        "median_cycle_time_hours_non_ai": non_ai_cycle,
        "cycle_time_delta_pct": delta_pct,
        "note": (
            "Positive delta = AI-flagged PRs took longer to merge; negative = faster. "
            "Detection is keyword/label-based and will miss undisclosed AI usage."
        ),
    }
